sudo: required
dist: trusty
addons:
  postgresql: "9.5"

env:      
  - PGVERSION=9.5

before_install:
  - sudo apt-get update
  - sudo apt-get install postgresql-server-dev-$PGVERSION postgresql-common
  - sudo apt-get install postgresql-$PGVERSION-postgis-2.3
  - psql -c "CREATE EXTENSION postgis"
  - git clone https://github.com/petere/plsh
  - cd plsh
  - make all PG_CONFIG=/usr/lib/postgresql/$PGVERSION/bin/pg_config
  - sudo make install PG_CONFIG=/usr/lib/postgresql/$PGVERSION/bin/pg_config
  - psql -U postgres -c "CREATE EXTENSION plsh"
  - cd ../
  
script:
  - make build PG_CONFIG=/usr/lib/postgresql/$PGVERSION/bin/pg_config
  - sudo make install PG_CONFIG=/usr/lib/postgresql/$PGVERSION/bin/pg_config
  - psql -U postgres -c "CREATE EXTENSION frapi"
  - psql -U postgres -c "SELECT * FROM frapi.adresse_search('route des anges, landéda')"
