sudo: required
dist: trusty

env:
  - PGVERSION=9.5 POSTGISVERSION=2.3
  - PGVERSION=9.6 POSTGISVERSION=2.3
   
before_install:
  - bash ./TEST/pg-travis-install.sh
  - PGPORT=55435 psql -U postgres -c "CREATE EXTENSION postgis"
  - PGPORT=55435 psql -U postgres -c "CREATE EXTENSION plsh"
  - PGPORT=55435 psql -U postgres -c "CREATE EXTENSION pgtap" #Only needed for test

install:
  - make build PG_CONFIG=/usr/lib/postgresql/$PGVERSION/bin/pg_config #Only really needed for dev related branch but harmless in master
  - sudo make install PG_CONFIG=/usr/lib/postgresql/$PGVERSION/bin/pg_config
  - PGPORT=55435 psql -U postgres -c "CREATE EXTENSION frapi"

script:
  - PGPORT=55435 make test PGUSER=postgres PG_CONFIG=/usr/lib/postgresql/$PGVERSION/bin/pg_config
