dist: trusty

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y
      postgresql-9.5 postgresql-server-dev-9.5 postgresql-9.5-postgis
      build-essential
  - psql -U postgres -c "CREATE EXTENSION postgis"
  - git clone https://github.com/petere/plsh
  - cd plsh && make
  - cd plsh && sudo make install
  - psql -U postgres -c "CREATE EXTENSION plsh"
  
script:
  - make build
  - sudo make install
  - psql -U postgres -c "CREATE EXTENSION frapi"
  - psql -U postgres -c "SELECT * FROM frapi.adresse_search('route des anges, landéda')"
