addons:
  postgresql: "9.5"
  
services:
  - postgresql

before_install:
  - psql -U postgres -c "CREATE EXTENSION postgis"
  
script:
  - make build
  - sudo make install
  - psql -U postgres "CREATE EXTENSION frapi"
